name: "Flake.lock: update Nix dependencies"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  nix-flake-update:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      NIX_CONFIG: |
        extra-substituters = https://nix-cache.bovbel.com/nixos
        extra-trusted-public-keys = nixos:pmAv4w1X/hCdM7rOjkK954hzdzEFiOgZshQmwWDpKNE=
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/determinate-nix-action@v3

      - name: Join Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github-action

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update Nix flake inputs"
          pr-labels:
            dependencies
            automated
