name: Update dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: read

concurrency:
  group: update-deps-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix:
    if: github.ref == 'refs/heads/main'
    runs-on: [self-hosted, nix-media]
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Update flake inputs
        run: nix flake update

      - name: Update Caddy plugins
        run: nix develop --command python3 modules/caddy/scripts/update.py
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create Nix dependency update PR
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.DEPENDENCY_UPDATE_TOKEN }}
          add-paths: |
            flake.lock
            modules/caddy/container.nix
          branch: update-nix-dependencies
          commit-message: "Update Nix dependencies"
          delete-branch: true
          title: "Update Nix dependencies"
          body: "Automated updates to Nix flake inputs and Caddy plugins."
          labels: |
            dependencies
            automated
